services:
  api:
    container_name: go-react-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file: ./apps/api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./apps/api:/go/src/app:cached
    tty: true
    command: ["sleep", "infinity"]
  db:
    image: postgres:15.2
    container_name: go-react-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_react

volumes:
  db-store:
